In [1]:
import numpy as np

In [2]:
# Answer here
x = np.array([4, 5])
y = np.array([7, 10])
print("Original vectors:")
print(x)
print(y)
print("Inner product of said vectors:")
print(np.multiply(x, y))

Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
[28 50]


In [3]:
# Answer here
a = np.array([[1, 0], [1, 2]])
print("Original 2-d array")
print(a)
print("Determinant of the said 2-D array:")
print(a**2)

Original 2-d array
[[1 0]
 [1 2]]
Determinant of the said 2-D array:
[[1 0]
 [1 4]]


In [6]:
a = np.array([1,2,np.nan,np.nan])
np.isnan(a).sum()

2

In [7]:
x = np.array([4, 5])
y = np.array([7, 10])

np.inner(x,y)

78

In [8]:
a = np.array([[1, 0], [1, 2]])
np.linalg.det(a)

2.0

In [9]:
a = np.array([[1, 0], [1, 2]])
np.linalg.inv(a)

array([[ 1. ,  0. ],
       [-0.5,  0.5]])

In [10]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.arange(4).reshape((2,2)).flatten()

array([0, 1, 2, 3])

In [16]:
a = np.arange(4).reshape((2,2))

np.amin(a,axis=1)

array([0, 2])

In [19]:
x = np.array([-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2.0])
np.ceil(x)

array([-1., -1., -0.,  1.,  2.,  2.,  2.])

In [20]:
np.floor(x)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

In [21]:
np.trunc(x)

array([-1., -1., -0.,  0.,  1.,  1.,  2.])

In [29]:
np.power(x,4)

array([6.55360e+00, 5.06250e+00, 8.10000e-03, 1.00000e-04, 3.84160e+00,
       1.04976e+01, 1.60000e+01])

In [30]:
np.log10(x)

C:\Users\AhmedRostom\AppData\Local\Temp\ipykernel_13328\1114196279.py:1: RuntimeWarning: invalid value encountered in log10
  np.log10(x)


array([        nan,         nan,         nan, -1.        ,  0.14612804,
        0.25527251,  0.30103   ])

In [31]:
np.log2(x)

C:\Users\AhmedRostom\AppData\Local\Temp\ipykernel_13328\3275510840.py:1: RuntimeWarning: invalid value encountered in log2
  np.log2(x)


array([        nan,         nan,         nan, -3.32192809,  0.48542683,
        0.84799691,  1.        ])